project_id = "eexnsbcfuovpdjxphcmy"

[functions.generate-sentiments]
verify_jwt = false

[functions.therapy-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.protocol-executor]
verify_jwt = false

[functions.audio-assembly]
verify_jwt = false