project_id = "kajrbruhcpaahhoitwtv"

[api]
enabled = true
port = 54331
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54332
shadow_port = 54333
major_version = 15

[studio]
enabled = true
port = 54334
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54335
smtp_port = 54336
pop3_port = 54337

[analytics]
enabled = true
port = 54338

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://localhost:5173"]

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[functions.generate-sentiments]
verify_jwt = false

[functions.therapy-chat]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.protocol-executor]
verify_jwt = false

[functions.audio-assembly]
verify_jwt = false

[functions.generate-voice-sample-text]
verify_jwt = false

[functions.voice-cloning]
verify_jwt = false

[functions.voice-clone-test]
verify_jwt = false

[functions.voice-clone-confirm]
verify_jwt = false

[functions.generate-audio-item]
verify_jwt = false

[functions.notification-service]
verify_jwt = false

[functions.batch-generate-audio-items]
verify_jwt = false

[functions.generate-session-title]
verify_jwt = false

[functions.credit-tracking]
verify_jwt = false

[functions.pause-session]
verify_jwt = false